// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fast_ibs
NumericMatrix fast_ibs(SEXP M_, int block_size, bool diagonal_trueIBS, int min_sites, int n_threads);
RcppExport SEXP _ibsdist_fast_ibs(SEXP M_SEXP, SEXP block_sizeSEXP, SEXP diagonal_trueIBSSEXP, SEXP min_sitesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_(M_SEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal_trueIBS(diagonal_trueIBSSEXP);
    Rcpp::traits::input_parameter< int >::type min_sites(min_sitesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ibs(M_, block_size, diagonal_trueIBS, min_sites, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ibsdist_fast_ibs", (DL_FUNC) &_ibsdist_fast_ibs, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ibsdist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
