# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_ibs <- function(M_, block_size = 256L, diagonal_trueIBS = FALSE, min_sites = 0L, n_threads = 0L) {
    .Call(`_ibsdist_fast_ibs`, M_, block_size, diagonal_trueIBS, min_sites, n_threads)
}

